#pragma once

#include "quantum.h"

#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_BREATHING

/** Tap/hold settings. */
#define TAPPING_TERM 200
#define HOLD_ON_OTHER_KEY_PRESS

